### ISSUE TITLE
negative literals are unconstrained

### ISSUE THREAD

**Issue by jacereda** [zetzit/zz#112]
If I set `temp` below to `3` it works correctly, but passing negative values fails.

```c++
const i8 THRESHOLD = 10;

pub theory cold(i8 degrees) -> bool
(
    degrees < THRESHOLD
)

export fn main() -> int {
    i8 temp = -3;
    static_assert(cold(temp));
    return 0;
}
```

**Comment by aep** [comment]
Looks like a bug to me. Probably passing the wrong type for i8 to ssa.

**Comment by jacereda** [comment]
s/i8/int/g yields the same result.

**Comment by aep** [comment]
can reproduce. the ssa looks fine, except it lacks any literal value. It is emitted as raw C literal.
