### ISSUE TITLE
Move vim support to separate repository

### ISSUE THREAD

**Issue by jam1garner** [zetzit/zz#144]
I suggest this because it would then likely be better for supporting most vim plugin managers as then you'd only need to do, using plug as an example, the following:

```vim
call plug#begin('~/.vim/plugged')

Plug 'zetzit/zz.vim'

call plug#end()
```

(It's also a bit easier for anyone who wants to manually install it too)

**Comment by jwerle** [comment]
I am not opposed to this. What are your thoughts @aep ?

**Comment by aep** [comment]
yes this makes sense
