### ISSUE TITLE
zz shouldn't try to create an index in read only directory

### ISSUE THREAD

**Issue by sternenseemann** [zetzit/zz#157]
In the `zz` version packaged for NixOS, we install the modules shipped with the compiler globally into a read-only file system. This means that compiling anything with dependencies on that library will fail with:

```
finished parsing ::mem
thread 'main' panicked at 'cannot create target/repos: Os { code: 30, kind: Other, message: "Read-only file system" }', src/repos.rs:27:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by aep** [comment]
oh yeah, that's a probem for all distros.

**Comment by aep** [comment]
quickfix looks easy actually. we can just not write a cachefile if there are no repos

**Comment by aep** [comment]
please let me know if its not fixed
