### ISSUE TITLE
Yices does not work out of the box

### ISSUE THREAD

**Issue by richardanaya** [zetzit/zz#49]
I ran the suggested commands to run hello on the Readme.md and it gave me an error message about not finding `z3`

Maybe remove the suggestion of installing yices if it doens't work?

**Comment by aep** [comment]
yices is a little confusing. you need yices_smt2_mt, which may or may not be in your distros package.

**Comment by aep** [comment]
the behaviour of finding yices has changed, does it work for you now?

**Comment by aep** [comment]
closing this due to lack of response. 

feel free to reopen if it still doesnt work :)
