### ISSUE TITLE
Make hello example simpler

### ISSUE THREAD

**Issue by richardanaya** [zetzit/zz#50]
I looked into this project and it was cognitive overload of what was happening. I think a simpler example would give someone a clearer picture whats going on.

**Comment by aep** [comment]
i think there's a need for a much more structured documentation anyway, in the form of an mdbook

**Comment by richardanaya** [comment]
that would be awesome!

**Comment by johnwcowan** [comment]
I strongly agree.  I'm one of those people who learns languages by devouring the reference manual, and for me K & R is exactly what such a manual should look like.  

Even something as simple as a BNF-ish grammar would be very helpful.  Trying to guess the syntax by looking at examples just doesn't work for me.

**Comment by jwerle** [comment]
@johnwcowan here are a few examples of it in the wild

- https://github.com/aep/zztop
- https://github.com/devguardio/carrier/tree/zz
- https://github.com/zx-project/zx
- https://github.com/little-core-labs/varint-wasm
- https://github.com/little-core-labs/hyperid-wasm
- https://github.com/little-core-labs/base64-wasm

**Comment by aep** [comment]
@johnwcowan see the formal PEG here https://github.com/zetzit/zz/blob/master/src/zz.pest


let me know if it is readable. i too enjoy learning languages from their formal definition

**Comment by johnwcowan** [comment]
Thanks, this is great!

**Comment by jwerle** [comment]
We've added some examples to a repository here: https://github.com/little-core-labs/zz-examples and in an effort to share ZZ on Twitter, we've been sharing through an unofficial account: https://twitter.com/zetztweets

**Comment by aep** [comment]
@jwerle thats amazing! Thank you so much.

If you'd like to add me (@ arvidep) to that twitter account, here's how to use shared accounts: https://help.twitter.com/en/using-twitter/tweetdeck-teams

**Comment by jwerle** [comment]
@aep done!

**Comment by aep** [comment]
dup of #82
