### ISSUE TITLE
Introduction of 'seanmonstar/reqwest' causes `openssl` dependency

### ISSUE THREAD

**Issue by jwerle** [zetzit/zz#58]
This commit (610295b9) introduced the [reqwest crate](https://docs.rs/reqwest/0.10.4/reqwest/) [requiring users to install openssl](https://github.com/seanmonstar/reqwest#requirements) on Linux. This should be documented somewhere

**Comment by aep** [comment]
Actually that's not supposed to be there. I must have left it in by accident. Thanks for noticing.
