### ISSUE TITLE
borrow() implementation

### ISSUE THREAD

**Issue by jwerle** [zetzit/zz#68]
I am not sure I have fully understood how this works yet. I can see that: if a module exports a `borrow` function, it will automatically be called during compilation triggering any theories attached to it. Is that correct? Does that make sense?

**Comment by aep** [comment]
yeah. Their intent is to carry a bunch of clauses that are automatically checked whenever a pointer is passed. Unfortunately it's pretty terrible due to lack of infrastructure for what "borrow" actually is. I'll have to do that first before this feature becomes useful.

**Comment by jwerle** [comment]
Seems powerful. I've brushed up against the `borrow()` implementation for the `slice` module (`Slice` and `MutSlice`). Finally grok'd last night

**Comment by aep** [comment]
yeah it will be pretty good once it works. but right now i don't recommend using it because i'll definitely break it. It also slows down the prover dramatically

**Comment by jwerle** [comment]
i'll stay away until there is a signal stability. Should I stay away from `Slice` and `MutSlice` because they implement `borrow()` or just don't implement a `borrow()` for my module code?

**Comment by aep** [comment]
nah, everything that has tests must always pass.
i'll fix slice when i break borrow :)

**Comment by jwerle** [comment]
hell yeah :]

**Comment by jwerle** [comment]
closing for now
