### ISSUE TITLE
Move 'mem' field member in 'Slice' to first position

### ISSUE THREAD

**Issue by jwerle** [zetzit/zz#71]
hey @aep, I hope all is well. What are your thoughts on  moving the [`mem`](https://github.com/zetzit/zz/blob/master/modules/slice/src/slice.zz#L6) field to the first position for the `Slice` struct? This would line up with structures like [`struct iovec`](https://code.woboq.org/gcc/include/bits/types/struct_iovec.h.html#iovec::iov_base) and [others](https://github.com/libuv/libuv/blob/v1.x/include/uv/unix.h#L121).

The main use case would be casting a `Slice` to `struct iovec` or `uv_buf_t`.

**Comment by aep** [comment]
that's a really good idea

**Comment by jwerle** [comment]
cool I issued a PR :upside_down_face:
