### ISSUE TITLE
Fix Windows CI

### ISSUE THREAD

**Issue by jwerle** [zetzit/zz#76]
Currently, Windows builds are failing: https://travis-ci.com/github/zetzit/zz/jobs/352190318

**Comment by jwerle** [comment]
I am investigating this

**Comment by aep** [comment]
Yeah I tried fixing it but I'm really lost. It works fine on my windows machine.

**Comment by jwerle** [comment]
Found the issue. The [empty `z3` directory](https://github.com/jwerle/zz/blob/fix-win-ci/.travis.yml#L15) in the extracted output was causing a PATH conflict. It is odd that `PATHEXT` is not honored [here](https://github.com/jwerle/zz/blob/fix-win-ci/.travis.yml#L17) when that directory exists AND `z3.exe`

**Comment by aep** [comment]
whuut, you're a hero
