### ISSUE TITLE
Module Symbol Exports

### ISSUE THREAD

**Issue by jwerle** [zetzit/zz#81]
Looking around at the docs emitter, it doesn't seem too difficult to emit all the parsed symbols in the loaded modules to something like JSON. This could make it easier to expose ZZ symbols in a module to other systems for tooling.

What are your thoughts on this @aep?

**Comment by aep** [comment]
uuuh which stage are you thinking about? you mean like export the functions and globals?

the verification is already exported as SMT.

**Comment by jwerle** [comment]
Nice, didn't know that. I'll check it out. As far as stages, not sure. I need to dive into that part of the code

**Comment by aep** [comment]
is this still relevant?

**Comment by jwerle** [comment]
Nope
