### ISSUE TITLE
Reference to module root

### ISSUE THREAD

**Issue by jwerle** [zetzit/zz#89]
It would be pretty convenient to support an identifier or keyword that references the root of the module much like certain usage of Rust's `crate`  keyword.

@aep what are your thoughts?

**Comment by aep** [comment]
Yes!

**Comment by aep** [comment]
Actually an absolute path might work already.

    using ::string;

**Comment by jwerle** [comment]
hmm, it doesn't seem to work if I want to do something like:

```c++
// a.zz

export fn foo() -> int {
  return 123;
}
```
```c++

// b.zz

export fn bar() -> int {
  return ::a::foo();
}
```

```c++
// lib.zz
export using a::{ foo }
export using b::{ bar }
```

**Comment by aep** [comment]
oh in b.zz you can just do "using a"
