### ISSUE TITLE
Looking forward to zulip chat room

### ISSUE THREAD

**Issue by damon-kwok** [zetzit/zz#93]
https://zetz.zulipchat.com

**Comment by jwerle** [comment]
Zulip looks interesting. We already have an IRC channel going `#zetz`

**Comment by aep** [comment]
since multiple people asked, i created the zulip thing. let me know if i should change any settings.

**Comment by damon-kwok** [comment]
@aep This site is currently unregistered and needs to be invited to join.

**Comment by aep** [comment]
oh i didnt realize it works like discord i guess.

here's the invite link

https://zetz.zulipchat.com/join/5c4eoaqmwjdxmcrlvaxx7itw/
